#!/usr/bin/env bash
# validate brew is installed

echo "Installing Homebrew utilities"
brew install \
    composer \
    fpp \
    # Github CLI
    gh \
    gpg \
    jq \
    kubectl \
    kustomize \
    npm \
    php \
    ripgrep \
    tree

echo "Installing Homebrew casks"
brew install --cask \
    docker \
    iterm2 \
    # Mouse scroll direction
    linearmouse \
    # Window manager
    rectangle \
    sequel-ace
