#!/usr/bin/env bash
echo "Step 3 - Configuring"

echo "Closing System Settings"
killall "System Settings"

echo "System-wide preferences"
echo "  Disable autocorrect"
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
echo "  Disable automatic capitalization"
defaults write -g NSAutomaticCapitalizationEnabled -bool false
echo "  Disable two spaces to period"
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
echo "  Adding keyboard shortcuts for navigating tabs"
defaults write -g NSUserKeyEquivalents -dict-add "Select Next Tab" "@~\\U2192"
defaults write -g NSUserKeyEquivalents -dict-add "Select Previous Tab" "@~\\U2190"
defaults write -g NSUserKeyEquivalents -dict-add "Show Next Tab" "@~\\U2192"
defaults write -g NSUserKeyEquivalents -dict-add "Show Previous Tab" "@~\\U2190"
echo "  Don't show slow thumbnail when taking screenshots"
defaults write com.apple.screencapture show-thumbnail -bool false
echo "  Require password after screen saver starts (this will ask for your password)"
sysadminctl -screenLock 5 -password -


echo "Safari"
defaults write -app Safari AlwaysRestoreSessionAtLaunch -bool true
defaults write -app Safari ExcludePrivateWindowWhenRestoringSessionAtLaunch -bool true
defaults write -app Safari FindOnPageMatchesWordStartsOnly -bool false
defaults write -app Safari OpenPrivateWindowWhenNotRestoringSessionAtLaunch -bool false
defaults write -app Safari ShowFullURLInSmartSearchField -bool true
defaults write -app Safari ShowOverlayStatusBar -bool true
echo "  Dev Tools"
# These do not appear to work, despite diffing the plist
# defaults write -app Safari IncludeDevelopMenu -bool true
# defaults write -app Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
# defaults write -app Safari WebKitPreferences.developerExtrasEnabled -bool true
echo "    Develop menu needs manual configuration, it won't work here"
# Leave this off - debug is for developrs OF Safari
# defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

echo "Finder"
echo "  Various drives on Desktop"
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
echo "  Status bar"
defaults write com.apple.finder ShowStatusBar -bool true
echo "  Path bar"
defaults write com.apple.finder ShowPathbar -bool true
echo "  New windows open to $HOME"
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
echo "  Use column view"
defaults write com.apple.finder FXPreferredViewStyle clmv
defaults write com.apple.finder ShowSidebar -bool true

echo "Dock"
echo "  Top right hot corner: lock screen"
defaults write com.apple.dock wvous-tr-corner -int 13
defaults write com.apple.dock wvous-tr-modifier -int 0

echo "iTerm2"
defaults write com.googlecode.iterm2 PrefsCustomFolder $HOME/dev/github/firehed/settings/iterm
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

echo "Restarting applications"
killall Finder
killall Dock
