#!/usr/bin/env bash
echo "Step 3 - Configuring"

echo "Disable autocorrect"
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
echo "Disable automatic capitalization"
defaults write -g NSAutomaticCapitalizationEnabled -bool false
echo "Disable two spaces to period"
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false

echo "Configuring iTerm2"
defaults write com.googlecode.iterm2 PrefsCustomFolder $HOME/dev/github/firehed/settings/iterm
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
