#!/usr/bin/env bash

# Install Homebrew
if command -v brew &> /dev/null
then
    echo "Brew is already installed"
    exit 0
fi

echo "Installing Homebrew..."

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
